# Generated by Django 6.0.3 on 2026-04-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='element',
        ),
    ]
