# Generated by Django 6.0.3 on 2026-04-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0002_remove_comment_element'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.element'),
        ),
    ]
